#appspec.yml
version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ec2-user/jungsuri #이곳으로 파일들을 모두 옮김
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: script/jungsuri-deploy.sh
      timeout: 60
      runas: ec2-user

#hooks:
#  AfterInstall:
#    - location: scripts/stop.sh
#      timeout: 60
#      runas: ubuntu
#  ApplicationStart:
#    - location: scripts/start.sh
#      timeout: 60
#      runas: ubuntu