#appspec.yml
version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ec2-user/jungsuri
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
#    group: ubuntu

hooks:
  ApplicationStart:
    - location: script/jungsuri-deploy.sh
      timeout: 60
      runas: ubuntu

#hooks:
#  AfterInstall:
#    - location: scripts/stop.sh
#      timeout: 60
#      runas: ubuntu
#  ApplicationStart:
#    - location: scripts/start.sh
#      timeout: 60
#      runas: ubuntu