version: '3.1'

services:
  jungsuri:  # 컨테이너 이름
    build:  # Dockerfile의 빌드 설정
      context: ./  # Dockerfile이 있는 디렉터리 경로
      dockerfile: dockerfile  # Dockerfile의 이름
    image: jungsuri-image  # 이미지 이름 (나중에 사용할 수 있도록 이름 설정)
    environment:
      SPRING_PROFILES_ACTIVE : dev
      dbLoginId : young
      dbPassword : 7dmldud9!!
      jooqVersion : 3.18.0
      mailSendLoginId : euiyoung1403
      mailSendPassword : uzbxqeqwunkivcug
      weatherAPIKey : 707030ec5c754c712499024828387e91
      MYSQL_ROOT_PASSWORD : 7dmldud9!!
      MYSQL_ALLOW_EMPTY_PASSWORD : 7dmldud9!!
      MYSQL_USER : young
      MYSQL_PASSWORD : 7dmldud9!!
      MYSQL_DATABASE : jungsuri
      MYSQL_RANDOM_ROOT_PASSWORD : 7dmldud9!!
    ports:
      - "8002:8002"
    depends_on:
      - jungsuri-db
    networks:
      - jungsuri-network
    volumes:
      - ./build/libs/jungsuri-0.0.1-SNAPSHOT.jar:/app/app.jar


  jungsuri-db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD : 7dmldud9!!
      MYSQL_DATABASE : jungsuri
      MYSQL_USER : young
      MYSQL_PASSWORD : 7dmldud9!!
      MYSQL_ALLOW_EMPTY_PASSWORD : yes
    ports:
      - "3306:3306"
    networks:
      - jungsuri-network

networks:
  jungsuri-network:
    driver: bridge
