spring.datasource.url=jdbc:mysql://localhost:3306/jungsuri?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=jungsuridb
spring.datasource.password=7dmldud9!!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.mvc.static-path-pattern=/resources/static/**
spring.thymeleaf.prefix=file:src/main/resources/templates/
spring.jpa.hibernate.ddl-auto=update
spring.mvc.hiddenmethod.filter.enabled=true

#thymeleaf.prefix=classpath: templates/
#mvc.static-path-pattern"/static/**"
#thymeleaf.suffix=.html
#thymeleaf.check-template-location=true
#thymeleaf.cache=false
