spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jungsuri
    username: young
    password: 7dmldud9!!
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mailSendLoginId}@gmail.com
    password: ${mailSendPassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  jooq:
    sql-dialect: mysql

spring.jpa.show-sql: true
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring.mvc.hiddenmethod.filter.enabled: true
