name: Build and Deploy

on:
  push:
    branches:
      - main  # 또는 원하는 브랜치로 변경

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions 실행 환경 선택

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

#      - name: Set up JDK 18
#        uses: actions/setup-java@v3
#        with:
#          java-version: '18'  # 사용할 Java 버전 설정

      - name: Build JAR
        run: |
          ./gradlew build  # 빌드 스크립트에 따라 변경 가능

      - name: Deploy to Docker
        run: |
          docker build -t jungsuri .
          docker run -p 8002:8002 --name jungsuri-container --network jungsuri-network -d 'ny2485/jungsuri'
