name: Build and Deploy

on:
  push:
    branches:
      - main  # 또는 원하는 브랜치로 변경

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions 실행 환경 선택

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # 사용할 Java 버전 설정

      - name: Build JAR
        run: |
          ./gradlew build  # 빌드 스크립트에 따라 변경 가능

      - name: Deploy to Docker
        run: |
          docker build -t my-java-app .
          docker run -d -p 8002:8002 my-java-app
